---
- name: Register Node with Ansible Automation Platform
  hosts: localhost
  tasks:
    - name: Register node
      uri:
        url: "https://192.168.122.61/api/v2/settings/system/"
        headers:
          Authorization: "Basic {{ 'admin:password' | b64encode }}"
        method: PUT
        body_format: json
        body: '{ "SUBSCRIPTIONS_USERNAME": "rh-ee-mcastrog"}'
          # Add more parameters as needed for your setup
        validate_certs: false
      register: response

    - name: Display API response
      debug:
        var: response
