---
- name: Register Node with Ansible Automation Platform
  hosts: localhost
  tasks:
    - name: manifest
      ansible.builtin.slurp:
        src: manifest_AAP_20240429T143755Z.zip
      register: ayu
    - name: manifest dos
      debug:
        var: ayu
    - name: decodificar
      set_fact:
        decoded_content: "{{ ayu | b64decode }}"
#    - name: manifest tres
 #     debug:
  #     msg: "{{ ayu['content'] |  b64decode }}"
    - name: Register node
      uri:
        url: "https://192.168.122.61/api/v2/settings/system/"
        headers:
          Authorization: "Basic {{ 'admin:password' | b64encode }}"
        method: PUT
        body_format: json
        body: '{
                "ACTIVITY_STREAM_ENABLED": true,
                "ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC": false,
                "ORG_ADMINS_CAN_SEE_ALL_USERS": true,
                "MANAGE_ORGANIZATION_AUTH": true,
                "TOWER_URL_BASE": "https://towerhost",
                "REMOTE_HOST_HEADERS": [
                "REMOTE_ADDR",
                "REMOTE_HOST"
                ],
                "PROXY_IP_ALLOWED_LIST": [],
                "CSRF_TRUSTED_ORIGINS": [],
                "LICENSE": "{{ decoded }}",
                "REDHAT_USERNAME": "",
                "REDHAT_PASSWORD": "",
                "SUBSCRIPTIONS_USERNAME": "rh-ee-mcastrog",
                "SUBSCRIPTIONS_PASSWORD": "CG091019",
                "DEFAULT_EXECUTION_ENVIRONMENT": null,
                "CUSTOM_VENV_PATHS": [],
                "INSIGHTS_TRACKING_STATE": false,
                "AUTOMATION_ANALYTICS_LAST_GATHER": null,
                "AUTOMATION_ANALYTICS_LAST_ENTRIES": "",
                "AUTOMATION_ANALYTICS_GATHER_INTERVAL": 14400,
                "UI_NEXT": true,
                "CLEANUP_HOST_METRICS_LAST_TS": null,
                "HOST_METRIC_SUMMARY_TASK_LAST_TS": null
            }'
              # Add more parameters as needed for your setup
        validate_certs: false
      register: response

    - name: Display API response
      debug:
        var: response
