- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello Message
      debug:
        msg: "Hello World!aaaaa"
        
    - name: Read a kv1 secret with the default mount point
      ansible.builtin.set_fact:
        response: "{{ lookup('community.hashi_vault.vault_kv1_get', 'cubbyhole/mario', url='http://192.168.122.254:8201') }}"
      # equivalent API path is kv/hello
    
    - name: Display the results
      ansible.builtin.debug:
        msg:
          - "Secret: {{ response.secret }}"
          - "Data: {{ response.data }} (same as secret in kv1)"
          - "Metadata: {{ response.metadata }} (response info in kv1)"
          - "Full response: {{ response.raw }}"
          - "Value of key 'password' in the secret: {{ response.secret.password }}"
