- name: Hello World Sample
  hosts: all
  vars_files: 
    - secret.yml
  tasks:
    - name: make sure hvac is available 
      pip: 
        name: hvac
        state: present
    - name: Hello Message
      debug:
        msg: "{{ hola }}"
    - name: Hello Message
      debug:
        msg: "Hello World!aaaaa"
        
    - name: Read 
      community.hashi_vault.vault_read:
        url: http://192.168.122.254:8200
        path: cubbyhole/mario
        auth_method: token
        token: hvs.G2Uo0JSlMIIaBK9lV9p2ULV8
      register: response
    
    - name: Display the secret data
      ansible.builtin.debug:
        msg: "{{ response.data.data.hola }}"
