---
- name: test1
  hosts: localhost
  tasks:
    - name: print
      debug:
        msg: "Hola Mundo"
    - name: Proyect update 
      ansible.controller.project_update:
        controller_host: 192.168.122.61
        validate_certs: false
        controller_username: "admin"
        controller_password: "password"
        project: "Test5"
