---
- name: test1
  hosts: localhost
  tasks:
    - name: print
      debug:
        msg: "Hola Mundo"
    - name: anadir permisos a jambo
      ansible.controller.role:
        controller_host: 192.168.122.61
        validate_certs: false
        controller_username: "admin"
        controller_password: "password"
        role: inventory_admin
        inventories: Demo Inventory
        user: jambo
        
