---
- name: test1
  hosts: localhost
  tasks:
    - name: print
      debug:
        msg: "Hola Mundo"
    - name: anadir grupo
      ansible.controller.group:
        name: grupos
        inventory: Demo Inventory
        hosts:
          - localhost
