- name: Remove license
  hosts: localhost
  tasks:
    - name: remove license
      ansible.controller.license:
        controller_host: "192.168.122.61"
        validate_certs: false
        controller_username: "admin"
        controller_password: "password"
        manifest: "manifest_AAP_20240429T143755Z.zip"

