---
- name: test1
  hosts: localhost
  tasks:
    - name: print
      debug:
        msg: "Hola Mundo"
    - name: variables
      ansible.controller.job_launch:
        controller_host: 192.168.122.61
        validate_certs: false
        controller_username: "admin"
        controller_password: "password"
        job_template: "extravariables"
        extra_vars:
          var1: "My First Variable"
          var2: "My Second Variable"
          var3: "My Third Variable"
          
