---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - name: Ansible urls
      ansible.eda.url_check:
        urls:
          - https://github.com/
      delay: 10

  rules:
    - name: Is up
      condition: event.url_check.status == "up"
      action:
        run_job_template:
          name: eda_hello
          organization: Default

    - name: Is down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: eda_adios
          organization: Default
